{
    "name":"task managements 2",
    "category":"Sales",
    "application":True,
    "installable":True,
    "license":"LGPL-3",
    "data":[
        'security/groups.xml',
        'security/record_rule.xml',
        'security/ir.model.access.csv',
        'data/category.managements.csv',
        'views/user.xml',
        'views/category.xml',
        'views/task.xml',
        'wizard/confirmation_wizard.xml',
        'views/menuitems.xml',
        'report/report_task_details_template.xml',
        'report/report_task_basic_template.xml',
        'report/report.xml',
    ],
    "depends":["base"]    
}